### ISSUE TITLE
Use localStorage in frontend to save/load desired and owned items

### ISSUE THREAD

**Issue by vuryleo** [penguin-statistics/ArkPlanner#10]
It's quite often that you clicked multiple times to adjust the value of requirements and/or owned items. But when you do a refresh, it's all gone away.
Maybe we could use localStorage to save these data and have a save/load button to read/write from it.

Multiple saving slots might be better.
Auto-save might help as well.

**Comment by vuryleo** [comment]
If you could point me to the right FE code base I may give it a try. The FE sub module looks like a compiled release other than source code itself.

**Comment by ycremar** [comment]
Frontend repo is consistent with the current backend now. Any contribution is appreciated!
https://github.com/ycremar/ArkPlanner-FrontEnd
