### ISSUE TITLE
英雄所见略同😄

### ISSUE THREAD

**Issue by gigaflw** [penguin-statistics/ArkPlanner#4]
就在差不多时间，我也写了一个差不多的东西， repo 在[这里](https://github.com/gigaflw/ArknightsPlanner)。
思路也差不多，都是线性规划。

但这里还有前端网站，这就厉害了，以后会来多多参考大佬的 repo 😄 

我本人没有服务器资源，所以没考虑发表的事，只想着自己用用，所以我觉得这个 repo 对大家更有用 👍 

提一个我自己觉得有用所以实现了，但在这里没看到的东西。就是需要的素材几乎都是被用来培养干员的，如果可以让用户指定干员的培养计划，而不用自己计算，那用户体验说不定可以更好。

🎉

**Comment by ycremar** [comment]
哈哈棒，简单看了下应该用的方法是一样的，可以顺便帮忙测试一下两个跑出来的结果一样不一样~
另外pengiun-stats的数据开放api直接获取的，不需要爬哈哈。另外有兴趣可以加企鹅物流数据群啊：747099627
