### ISSUE TITLE
申请跨域调用

### ISSUE THREAD

**Issue by Tsuk1ko** [penguin-statistics/ArkPlanner#6]
您好，我最近也参考 graueneko 写了一个[工具箱](https://arkn.lolicon.app)，无意间看到您的项目，十分想整合该项目的 API

我在材料计算器中已经实现了通过选择干员并设置精英化和技能来得到所需材料的功能，因此整合该项目可以变得更加懒人化（x

不知您意下如何 \_(:3」∠)\_

**Comment by ycremar** [comment]
已经见到好几个工具箱了哈哈，不过还是欢迎~跨域调用可以参考这类的用法。https://github.com/GachaSalt/ArkToolDemo

**Comment by Tsuk1ko** [comment]
感谢~

主要是想询问下是否可以直接跨域调用您的 API，因为我注意到`access-control-allow-origin: https://gachasalt.github.io`，又或者是更鼓励自行搭建后端使用？

**Comment by invisiblearts** [comment]
会在今天将 arkn.lolicon.app 加入 CORS 允许列表。

**Comment by Tsuk1ko** [comment]
@invisiblearts 感谢！

**Comment by invisiblearts** [comment]
@Tsuk1ko 已经允许了所有的 CORS 调用

**Comment by Tsuk1ko** [comment]
@invisiblearts 好的，谢谢
