### ISSUE TITLE
可使用 JS 实现

### ISSUE THREAD

**Issue by Tsuk1ko** [penguin-statistics/ArkPlanner#7]
@invisiblearts  经过寻找发现 [javascript-lp-solver](https://www.npmjs.com/package/javascript-lp-solver) 这个 npm 包可以做线性规划，尝试着按照 nga 帖子里说明的思路写了个简单的 [demo](https://gist.github.com/Tsuk1ko/124561025098a1ee8f3639ec2438f5a6)

这样的话就可以直接在前端计算了，不需要再依赖 python 后端，希望对你们的项目有帮助

这是D32钢、双极纳米片、聚合剂各 300 的运行结果，可能因为算法等因素的不同，和该项目的输出会略有不同

```javascript
{
	feasible: true,
	result: 284522.80033011,
	bounded: true,
	'合成-D32钢': 300,
	'合成-双极纳米片': 300,
	'合成-聚合剂': 300,
	'合成-RMA70-24': 196.71510358,
	'合成-五水研磨石': 253.26606141,
	'合成-三水锰矿': 300,
	'合成-白马醇': 503.56911835,
	'合成-改量装置': 236.47567779,
	'合成-酮阵列': 259.85815714,
	'合成-异铁块': 244.69642453,
	'合成-提纯源岩': 300,
	'合成-全新装置': 210.63986939,
	'合成-酮凝集组': 324.9097497,
	'合成-异铁组': 149.57573907,
	'合成-聚酸酯组': 401.5665748,
	'合成-糖组': 711.93773971,
	'合成-固源岩组': 1938.69714146,
	'合成-装置': 231.25252853,
	'合成-酮凝集': 558.57447716,
	'合成-异铁': 213.31308082,
	'合成-聚酸酯': 707.56054782,
	'合成-糖': 309.1893821,
	'合成-固源岩': 704.74319605,
	'4-9': 2279.44028345,
	'S3-1': 1410.82271421,
	'2-10': 23.07831898,
	'4-5': 950.02361441,
	'4-10': 1651.63237757,
	'1-7': 5886.48474204,
	'4-4': 1928.61763291,
	'3-2': 2261.35714303,
	'4-8': 1285.85093887,
	'S4-1': 1800.2267325
}
```

**Comment by invisiblearts** [comment]
感谢建议，有空的时候会尝试使用。
不过目前考虑到服务器流量的开销比较大（我把来自中国的请求解析到阿里云东京，目前大概一天2G左右），而把原始数据拉到本地大致会翻倍流量，可能会暂缓实现。
（Github Pages / 各种免费的 CDN 的话，国内的访问不太稳定；国内的服务的话，我又不太方便做备案）

**Comment by Tsuk1ko** [comment]
@invisiblearts 可以考虑国内 git 平台 coding.net 的 Pages 服务，位于 HK，访问会迅速很多，唯一的要求是需要将他们的 logo 放置到页面中

至于数据拉取消耗流量的问题，可能会影响到的只有企鹅物流那边，我是准备在 Service Worker 中，或者简单的使用 localStorage 做缓存（比如有效期一天）来减少数据拉取的次数（最多一天一次）
